version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/datasource

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - deps-{{ checksum "package.json" }}-
          - deps-

      - run: yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules

          key: deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
