name: Pre Release

on: push

jobs:
  versioning:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - run: echo ${{ steps.get-latest-tag.outputs }}
