name: Test Suite

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Load yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Run code linter
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Run unit tests
        run:  yarn run test:coverage

      - name: Report coverage
        run:  yarn run coverage:report

      - name: Upload coverage
        run: |
          curl --fail -o codecov https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov
          bash codecov -Z
